export default {
  COLLECT_CURRENCIES: "COLLECT_CURRENCIES",
  DISPLAY_CURRENCIES: "DISPLAY_CURRENCIES",
  PURCHASE_CURRENCY: "PURCHASE_CURRENCY",
  CHANGE_PAGINATION: "CHANGE_PAGINATION",
  CURRENCIES_LOADING: "CURRENCIES_LOADING",
};
